#!/bin/bash

self_dir=$(cd $(dirname $0) && pwd)
serv_dir=$self_dir/_docks

list_services()
{
    (cd $serv_dir; ls *-serv | sed 's/-serv$//g' | tr '\n' ' ')
}

usage()
{
    local cmd=$(basename $0)
    cat << EOF
usage: $cmd <service-name> [arguments]

services: $(list_services)
EOF
    exit 1
}

service_name=$1

[ -z "$service_name" ] && usage

$serv_dir/driver.sh "$@"

