#!/bin/bash

storage_dir=~/data/mysql/01
mysql_password=root

export CMD_NAME=$(basename $0)
export CONTAINER_NAME=mysql-01
export DOCKER_RUN="
    docker run -d \
        --name $CONTAINER_NAME \
        --env MYSQL_ROOT_PASSWORD=$mysql_password \
        -p 3306:3306 \
        -v $storage_dir:/var/lib/mysql \
        mysql:8.0
"

self_dir=$(cd $(dirname $0) && pwd)

$self_dir/serv-base "$@"

