#!/bin/bash

usage()
{
    local cmd=$(basename $0)
    cat << EOF
usage:
    $cmd <sub-command>

sub-command:
    create
        create docker container

    container-name
        show container name
EOF
    exit 1
}

cmd=$1
container_name=pg-01

[ -z $cmd ] && usage

self_dir=$(cd $(dirname $0) && pwd)

case $cmd in
    create)
        docker run --name $container_name --env POSTGRES_PASSWORD=postgres -p 5432:5432 -d "postgres:14.2"
        ;;
    container-name)
        echo $container_name
        ;;
    *)
        ;;
esac

