#!/bin/bash

storage_dir=~/data/pg/01
pg_password=postgres

export CMD_NAME=$(basename $0)
export CONTAINER_NAME=pg-01
export DOCKER_RUN="
    docker run -d \
        --name $CONTAINER_NAME \
        --env POSTGRES_PASSWORD=$pg_password \
        -p 5432:5432 \
        -v $storage_dir:/var/lib/postgresql/data \
        postgres:14.2
"

self_dir=$(cd $(dirname $0) && pwd)

$self_dir/serv-base "$@"

