#!/bin/bash

storage_dir=~/data/pulsar/01

export CMD_NAME=$(basename $0)
export CONTAINER_NAME=pulsar-01
export DOCKER_RUN="
    docker run -d \
        --name $CONTAINER_NAME \
        -p 6650:6650 \
        -p 8080:8080 \
        -v $storage_dir:/pulsar/data \
        apachepulsar/pulsar:latest \
        bin/pulsar standalone
"

self_dir=$(cd $(dirname $0) && pwd)

$self_dir/serv-base "$@"

